tasks:
  - init: echo "Replace me with a build script for the project."
    command: gem install jekyll bundler
    command: bundle install
    command: bundle exec jekyll build
    command: bundle exec jekyll serve