---
title: Great Bonefishing
author: Matt
email: GreatBonefishing@gmail.com
description: GBF
baseurl: ""
url: https://fishing.tk
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-sitemap
  - jekyll-sass-converter

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
